# Generated by Django 4.2.7 on 2023-11-30 09:12

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.CharField(max_length=4000)),
                (
                    "comment_image",
                    models.ImageField(blank=True, null=True, upload_to="comment_image"),
                ),
                (
                    "post_date_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
