# Generated by Django 4.2.7 on 2023-11-27 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("others", "Others"),
                        ],
                        default="male",
                        max_length=20,
                    ),
                ),
                ("dob", models.DateField(blank=True, default=None, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("github", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profile_image"),
                ),
                (
                    "follow_requests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="follow_requests_received",
                        to="user_profile.userprofile",
                    ),
                ),
                (
                    "following",
                    models.ManyToManyField(
                        blank=True,
                        related_name="followers",
                        to="user_profile.userprofile",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
