# Generated by Django 4.2.7 on 2023-11-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='host',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/', null=True),
        ),
    ]
