# Generated by Django 4.2.7 on 2023-12-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
