# Generated by Django 4.2.6 on 2023-11-14 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0002_userprofile_follow_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='follow_requests',
            field=models.ManyToManyField(blank=True, related_name='follow_requests_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
