# Generated by Django 4.2.7 on 2023-11-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='follow_requests',
            field=models.ManyToManyField(blank=True, related_name='follow_requests_received', to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='user_profile.userprofile'),
        ),
    ]
