# Generated by Django 4.2.7 on 2023-11-26 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_userprofile_follow_requests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lives_in',
            new_name='github',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='studies_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='works_at',
        ),
    ]
