# Generated by Django 4.2.7 on 2023-11-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='down_vote_by',
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
