# Generated by Django 4.2.7 on 2023-11-26 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_message_to'),
        ('comments', '0002_alter_comment_id'),
        ('votes', '0002_remove_vote_down_vote_by_alter_vote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='posts.post'),
        ),
    ]
