# Generated by Django 4.2.6 on 2023-10-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.CharField(max_length=500000, null=True),
        ),
    ]
