# Generated by Django 4.2.6 on 2023-10-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
