# Generated by Django 4.2.7 on 2023-12-04 01:55

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.CharField(blank=True, default=None, max_length=3000, null=True, validators=[posts.models.validate_url]),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=3000, null=True, validators=[posts.models.validate_url]),
        ),
    ]
