# Generated by Django 4.2.7 on 2023-12-01 23:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foreign',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
