# Generated by Django 4.2.7 on 2023-11-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default=None, max_length=3000, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='origin',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='posts.categories'),
        ),
    ]
