# Generated by Django 4.2.7 on 2023-11-26 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_rename_lives_in_userprofile_github_and_more'),
        ('posts', '0004_categories_rename_category_post_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to='user_profile.userprofile'),
        ),
    ]
